# Release build script

trigger: none
pr: none

pool:
  vmImage: ubuntu-16.04

steps:
  - bash: |
      sudo npm install -g vsce

      PACKAGE_VERSION=$(cat git-mob-vs-code/version.txt)

      vsce publish -p $MARKET_KEY --packagePath git-mob-vs-code/git-mob-$PACKAGE_VERSION.vsix
    workingDirectory: '$(System.DefaultWorkingDirectory)/_rkotze.git-mob-vs-code'
    displayName: Deploy
    env:
      MARKET_KEY: $(vscekey)
