# Release build script

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      npm install vsce

      PACKAGE_VERSION=$(cat git-mob-vs-code/version.txt)

      npm run vsix-publish -- -p $MARKET_KEY --packagePath git-mob-vs-code/git-mob-$PACKAGE_VERSION.vsix
    workingDirectory: '$(System.DefaultWorkingDirectory)/_rkotze.git-mob-vs-code'
    displayName: VS Market Deploy
    env:
      MARKET_KEY: $(vscekey)

  - bash: |

      PACKAGE_VERSION=$(cat git-mob-vs-code/version.txt)

      npm run ovsx-publish -- git-mob-vs-code/git-mob-$PACKAGE_VERSION.vsix -p $OPEN_MARKET_KEY
    workingDirectory: '$(System.DefaultWorkingDirectory)/_rkotze.git-mob-vs-code'
    displayName: Open Market Deploy
    env:
      OPEN_MARKET_KEY: $(ovsxkey)
